#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-NeedsDisplay
Version  : 1.07
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Test-NeedsDisplay-1.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Test-NeedsDisplay-1.07.tar.gz
Summary  : 'Ensure that tests needing a display have one'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
Requires: perl-Test-NeedsDisplay-license = %{version}-%{release}
Requires: xauth
Requires: xkbcomp
Requires: xkeyboard-config
Requires: xvfb-run
BuildRequires : buildreq-cpan
BuildRequires : perl(Module::Install)
BuildRequires : util-linux
BuildRequires : xauth
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xvfb-run

%description
NAME
Test::NeedsDisplay - Ensure that tests needing a display have one
SYNOPSIS
In your Makefile.PL...

%package dev
Summary: dev components for the perl-Test-NeedsDisplay package.
Group: Development
Provides: perl-Test-NeedsDisplay-devel = %{version}-%{release}
Requires: perl-Test-NeedsDisplay = %{version}-%{release}

%description dev
dev components for the perl-Test-NeedsDisplay package.


%package license
Summary: license components for the perl-Test-NeedsDisplay package.
Group: Default

%description license
license components for the perl-Test-NeedsDisplay package.


%prep
%setup -q -n Test-NeedsDisplay-1.07

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-NeedsDisplay
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-NeedsDisplay/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Test/NeedsDisplay.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::NeedsDisplay.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-NeedsDisplay/LICENSE
